### PR TITLE
Updated rootfs/etc/pam.d/duo

### LINKED ISSUE #38: PAM: Module is unknown for root from <IP>
So I was testing the project on AWS EC2 instance in docker container. After a fairly quick setup I received the following error when trying to login (server logs);
```
PAM: Module is unknown for root from <IP>
Connection closed by authenticating user root <IP> port 3445 [preauth]
```

The following is an original SSH command executed from my local host;
```
ssh -p 1234 root@<ip>
```

Key authentication passed successfully and I was prompted for SSH key password.

This is a `Makefile` I've used to setup the whole thing on EC2 instance;
```
SHELL := bash
MAKEFLAGS += --warn-undefined-variables
.SHELLFLAGS := -euo pipefail -c


DOCKER_OPTS := \
        -it \
        -e MFA_PROVIDER=duo \
        -e DUO_IKEY=<redacted> \
        -e DUO_SKEY=<redacted> \
        -e DUO_HOST=<redacted> \
        -e SLACK_ENABLED=true \
        -e SLACK_WEBHOOK_URL=<redacted> \
        -v `pwd`/authorized_keys:/root/.ssh/authorized_keys \
        -p 1234:22

.PHONY: all
all:

.PHONY: dbuild
dbuild:
        docker build . -t cloudposse/bastion:latest

.PHONY: drun
drun: dbuild
        docker run $(DOCKER_OPTS) \
                cloudposse/bastion:latest
```

I think the root cause is some DUO-related issues, probably related to https://github.com/cloudposse/bastion/issues/34.

Any clue where I went wrong with the setup?

### PR DESCRIPTION
**Pull request by paulcalabro**
Fixes #38

### CODE REVIEW

**Comment by osterman** [comment]
@paulcalabro - we did some necessary refactoring a number of months ago to facilitate long-term maintenance of this `Dockerfile`. In the process, it looks like we dropped something: `ln -s /lib /lib64`

What I like about the `ln` "fix" is that it addresses this class of problems, without needing to hardcode paths in the configs.

https://github.com/cloudposse/bastion/commit/8411230e466decf3a069fa3a5185c94bd5028d75#diff-3254677a7917c6c01f55212f86c57fbfR10

Would you mind giving this a shot and seeing it that fixes it?

**Comment by osterman** [comment]
We removed it in this commit by accident https://github.com/cloudposse/bastion/commit/e85859e513b67efc02fde9a67b20505c9f9b6177#diff-3254677a7917c6c01f55212f86c57fbfL10

**Comment by paulcalabro** [comment]
@osterman I actually came across the `ln` fix when I was reviewing the git blame history. The reason why I hard coded it was because it's already set explicitly to _lib64_ here:

https://github.com/cloudposse/bastion/blob/6f980527ebe77c9ac892a22e710909b0d9691713/Dockerfile#L19-L24

It looks like in a later stage, it's copied to _lib64_ in the final image as well. 

I reviewed the change log, but I'm a little unsure as to why the symlink is preferred if the module will always be located in this folder. Could you please clarify? 

I'll test out the symlink fix later today.

**Comment by osterman** [comment]
> I reviewed the change log, but I'm a little unsure as to why the symlink is preferred if the module will always be located in this folder. Could you please clarify?

I don't have a strong opinion on this.

My experience has been that I spend more time fixing these kinds of problems than I need to, so the general fix of symlinking `/lib64` to `/lib` eliminates this whole class of problems. On the other hand, editing the file itself with the explicit path, fixes it only for this one occurance. I find when installing precompiled binaries built on other distros, that I need to add this symlink anyways, which is why my bias exists towards the symlink.

**Comment by paulcalabro** [comment]
Thanks for the explanation as well as merging the PR! Cheers!

**Comment by osterman** [comment]
@paulcalabro thanks for taking the time to contribute the PR! =)

**Comment by paulcalabro** [comment]
Thanks for sharing this image. It's pretty awesome!

**Pull request merged**
